"""initial enterprise ai database

Revision ID: 4d67c7f8d597
Revises: b21d02f86729
Create Date: 2026-08-10 21:42:41.120906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d67c7f8d597'
down_revision: Union[str, Sequence[str], None] = 'b21d02f86729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'decision_history', 'decisions', ['decision_id'], ['decision_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decision_history', type_='foreignkey')
    # ### end Alembic commands ###
