"""add decision history

Revision ID: fb3dbe0a2e85
Revises: 4298498ed356
Create Date: 2026-08-10 04:43:32.687000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb3dbe0a2e85'
down_revision: Union[str, Sequence[str], None] = '4298498ed356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_count', sa.Integer(), nullable=False),
    sa.Column('predicted_sales', sa.Float(), nullable=False),
    sa.Column('inventory', sa.Float(), nullable=False),
    sa.Column('forecast_growth', sa.Float(), nullable=False),
    sa.Column('customer_churn', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('profit_margin', sa.Float(), nullable=False),
    sa.Column('customers', sa.Integer(), nullable=False),
    sa.Column('identified_risks', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('insights', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_history_created_at'), 'decision_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_history_decision_id'), 'decision_history', ['decision_id'], unique=True)
    op.create_index(op.f('ix_decision_history_id'), 'decision_history', ['id'], unique=False)
    op.create_index(op.f('ix_decision_history_risk_level'), 'decision_history', ['risk_level'], unique=False)
    op.drop_table('inventory_predictions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('sales_predictions')
    op.drop_table('reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('report_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
    )
    op.create_table('sales_predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prediction_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('sales_predictions_pkey'))
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('inventory_predictions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recommended_stock', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_predictions_pkey'))
    )
    op.drop_index(op.f('ix_decision_history_risk_level'), table_name='decision_history')
    op.drop_index(op.f('ix_decision_history_id'), table_name='decision_history')
    op.drop_index(op.f('ix_decision_history_decision_id'), table_name='decision_history')
    op.drop_index(op.f('ix_decision_history_created_at'), table_name='decision_history')
    op.drop_table('decision_history')
    # ### end Alembic commands ###
