
import {
    FileText,
    Download,
    FileJson,
    FileSpreadsheet,
    FileArchive,
} from "lucide-react";

export default function ReportFileList({ files = [] }) {

    const safeFiles = Array.isArray(files) ? files : [];

    // =====================================================
    // FILE NAME
    // =====================================================

    const getFileName = (file) => {

        if (typeof file === "string") {

            return file.split(/[\\/]/).pop();

        }

        if (file?.name) {

            return file.name;

        }

        if (file?.filename) {

            return file.filename;

        }

        if (file?.path) {

            return file.path.split(/[\\/]/).pop();

        }

        return "Report File";
    };


    // =====================================================
    // FILE URL
    // =====================================================

    const getFileUrl = (file) => {

        if (typeof file === "string") {

            if (
                file.startsWith("http://") ||
                file.startsWith("https://") ||
                file.startsWith("/")
            ) {
                return file;
            }

            return null;
        }

        return (
            file?.url ||
            file?.download_url ||
            file?.downloadUrl ||
            null
        );
    };


    // =====================================================
    // FILE ICON
    // =====================================================

    const getFileIcon = (fileName) => {

        const extension = fileName
            ?.split(".")
            .pop()
            ?.toLowerCase();


        if (extension === "json") {

            return (
                <FileJson
                    size={17}
                    className="text-yellow-400"
                />
            );
        }


        if (
            extension === "xlsx" ||
            extension === "xls" ||
            extension === "csv"
        ) {

            return (
                <FileSpreadsheet
                    size={17}
                    className="text-green-400"
                />
            );
        }


        if (
            extension === "zip" ||
            extension === "rar"
        ) {

            return (
                <FileArchive
                    size={17}
                    className="text-purple-400"
                />
            );
        }


        return (
            <FileText
                size={17}
                className="text-blue-400"
            />
        );
    };


    // =====================================================
    // RENDER
    // =====================================================

    return (

        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">

            {/* =====================================================
                HEADER
            ===================================================== */}

            <div className="flex items-center justify-between mb-5">

                <div className="flex items-center gap-2">

                    <FileText
                        size={20}
                        className="text-blue-400"
                    />

                    <div>

                        <h2 className="text-white font-bold text-xl">
                            Generated Report Files
                        </h2>

                        <p className="text-slate-500 text-xs mt-1">
                            Reports generated by the enterprise reporting engine.
                        </p>

                    </div>

                </div>


                {safeFiles.length > 0 && (

                    <span
                        className="
                            text-xs
                            text-slate-400
                            bg-slate-800
                            border
                            border-slate-700
                            rounded-full
                            px-3
                            py-1
                        "
                    >
                        {safeFiles.length}{" "}
                        {safeFiles.length === 1 ? "file" : "files"}
                    </span>

                )}

            </div>


            {/* =====================================================
                EMPTY STATE
            ===================================================== */}

            {safeFiles.length === 0 ? (

                <div
                    className="
                        border
                        border-dashed
                        border-slate-700
                        rounded-xl
                        py-10
                        px-5
                        text-center
                    "
                >

                    <FileText
                        size={32}
                        className="mx-auto text-slate-600 mb-3"
                    />

                    <p className="text-slate-400 text-sm">
                        No report files have been generated yet.
                    </p>

                    <p className="text-slate-600 text-xs mt-2">
                        Generated executive reports will appear here.
                    </p>

                </div>

            ) : (

                /* =================================================
                   FILE LIST
                ================================================= */

                <div className="space-y-2">

                    {safeFiles.map((file, index) => {

                        const fileName = getFileName(file);
                        const fileUrl = getFileUrl(file);

                        return (

                            <div
                                key={`${fileName}-${index}`}
                                className="
                                    flex
                                    items-center
                                    justify-between
                                    gap-3
                                    bg-slate-800/50
                                    hover:bg-slate-800
                                    border
                                    border-slate-800
                                    hover:border-slate-700
                                    rounded-lg
                                    px-4
                                    py-3
                                    transition
                                "
                            >

                                {/* FILE INFORMATION */}

                                <div className="flex items-center gap-3 min-w-0">

                                    <div
                                        className="
                                            w-9
                                            h-9
                                            rounded-lg
                                            bg-slate-950
                                            border
                                            border-slate-800
                                            flex
                                            items-center
                                            justify-center
                                            shrink-0
                                        "
                                    >
                                        {getFileIcon(fileName)}
                                    </div>


                                    <div className="min-w-0">

                                        <p
                                            className="
                                                text-sm
                                                text-slate-200
                                                font-medium
                                                truncate
                                            "
                                            title={fileName}
                                        >
                                            {fileName}
                                        </p>

                                        <p className="text-xs text-slate-600 mt-1">
                                            Enterprise report
                                        </p>

                                    </div>

                                </div>


                                {/* DOWNLOAD */}

                                {fileUrl && (

                                    <a
                                        href={fileUrl}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        download
                                        className="
                                            flex
                                            items-center
                                            gap-2
                                            shrink-0
                                            text-xs
                                            text-slate-300
                                            bg-slate-950
                                            hover:bg-slate-700
                                            border
                                            border-slate-700
                                            rounded-lg
                                            px-3
                                            py-2
                                            transition
                                        "
                                    >

                                        <Download size={14} />

                                        Download

                                    </a>

                                )}

                            </div>

                        );

                    })}

                </div>

            )}

        </div>
    );
}

